runtime: python37
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
