runtime: python37
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: javascript
- url: /templates
  static_dir: html
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
